//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WareHouseJP.Website.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AgencyPackage
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AgencyPackage()
        {
            this.AgencyPackageItems = new HashSet<AgencyPackageItem>();
        }
    
        public System.Guid Id { get; set; }
        public string AgencyId { get; set; }
        public Nullable<int> DeliveryId { get; set; }
        public string DeliveryName { get; set; }
        public Nullable<System.Guid> ShipmentId { get; set; }
        public string TrackingCode { get; set; }
        public Nullable<double> Weigh { get; set; }
        public string Image { get; set; }
        public byte[] ImageBinary { get; set; }
        public string Notes { get; set; }
        public Nullable<System.DateTime> SentDate { get; set; }
        public string SendHour { get; set; }
        public Nullable<System.DateTime> ReceivedDate { get; set; }
        public string ReceivedHour { get; set; }
        public Nullable<bool> IsEdit { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<bool> IsDeclare { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<int> TrackingStatusId { get; set; }
    
        public virtual Agency Agency { get; set; }
        public virtual DeliveryCom DeliveryCom { get; set; }
        public virtual Shipment Shipment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AgencyPackageItem> AgencyPackageItems { get; set; }
    }
}
