//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WareHouseJP.Website.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailHistory
    {
        public System.Guid Id { get; set; }
        public string AgencyId { get; set; }
        public string EmailFrom { get; set; }
        public string EmailTo { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> SendDate { get; set; }
        public string SendHour { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public string UpdatedBy { get; set; }
    
        public virtual Agency Agency { get; set; }
    }
}
