//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WareHouseJP.Website.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExportGood
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ExportGood()
        {
            this.ExportGoodDetails = new HashSet<ExportGoodDetail>();
            this.ExportInvoices = new HashSet<ExportInvoice>();
            this.FlightGoods = new HashSet<FlightGood>();
            this.ShippingHAWBDetails = new HashSet<ShippingHAWBDetail>();
        }
    
        public System.Guid Id { get; set; }
        public string AirId { get; set; }
        public string AgencyId { get; set; }
        public string StaffId { get; set; }
        public string ShippingMarkVN { get; set; }
        public string Image { get; set; }
        public string ImageBase64 { get; set; }
        public byte[] ImageBinary { get; set; }
        public Nullable<double> Weigh { get; set; }
        public Nullable<int> SizeTableId { get; set; }
        public string SizeInput { get; set; }
        public Nullable<double> WeighInput { get; set; }
        public string Size { get; set; }
        public string Notes { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<bool> IsStaffConfirm { get; set; }
        public Nullable<System.DateTime> ExportDate { get; set; }
        public string ExportHour { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public string UpdatedBy { get; set; }
    
        public virtual Agency Agency { get; set; }
        public virtual AirInfo AirInfo { get; set; }
        public virtual SizeTable SizeTable { get; set; }
        public virtual Staff Staff { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExportGoodDetail> ExportGoodDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExportInvoice> ExportInvoices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FlightGood> FlightGoods { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShippingHAWBDetail> ShippingHAWBDetails { get; set; }
    }
}
