//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WareHouseJP.Website.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FlightBooking
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FlightBooking()
        {
            this.ClearanceAirs = new HashSet<ClearanceAir>();
            this.ClearanceHAWBs = new HashSet<ClearanceHAWB>();
            this.ClearanceMAWBs = new HashSet<ClearanceMAWB>();
            this.CustomsClearances = new HashSet<CustomsClearance>();
            this.FlightBookingHAWBs = new HashSet<FlightBookingHAWB>();
            this.FlightBookingMAWBs = new HashSet<FlightBookingMAWB>();
            this.FlightGoods = new HashSet<FlightGood>();
            this.Invoices = new HashSet<Invoice>();
        }
    
        public System.Guid Id { get; set; }
        public string AgencyId { get; set; }
        public string AirId { get; set; }
        public string FlightRouteId { get; set; }
        public string Code { get; set; }
        public Nullable<double> AutomaticTrackingCount { get; set; }
        public Nullable<double> EnterManuallyTrackingCount { get; set; }
        public Nullable<double> AutomaticWeigh { get; set; }
        public Nullable<double> EnterManuallyWeigh { get; set; }
        public Nullable<bool> IsBooking { get; set; }
        public Nullable<bool> IsClearance { get; set; }
        public Nullable<bool> IsFlightGood { get; set; }
        public Nullable<int> StatusId { get; set; }
        public string Size { get; set; }
        public string Image { get; set; }
        public byte[] ImageBinary { get; set; }
        public Nullable<System.DateTime> BookingDate { get; set; }
        public string BookingHour { get; set; }
        public string Notes { get; set; }
        public string StaffId { get; set; }
        public string StaffIdUpdate { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public string UpdatedBy { get; set; }
    
        public virtual Agency Agency { get; set; }
        public virtual AirInfo AirInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClearanceAir> ClearanceAirs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClearanceHAWB> ClearanceHAWBs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClearanceMAWB> ClearanceMAWBs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomsClearance> CustomsClearances { get; set; }
        public virtual FlightRoute FlightRoute { get; set; }
        public virtual Staff Staff { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FlightBookingHAWB> FlightBookingHAWBs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FlightBookingMAWB> FlightBookingMAWBs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FlightGood> FlightGoods { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Invoice> Invoices { get; set; }
    }
}
