//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WareHouseJP.Website.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PackageReturn
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PackageReturn()
        {
            this.ReturnDetails = new HashSet<ReturnDetail>();
            this.ReturnHAWBs = new HashSet<ReturnHAWB>();
        }
    
        public System.Guid Id { get; set; }
        public string AgencyId { get; set; }
        public string ReturnCode { get; set; }
        public Nullable<System.DateTime> ReturnDate { get; set; }
        public string ReturnHour { get; set; }
        public string ReturnImage { get; set; }
        public string ReturnImageBase64 { get; set; }
        public string Notes { get; set; }
        public Nullable<int> StatusId { get; set; }
        public string ReciveName { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public string UpdatedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReturnDetail> ReturnDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReturnHAWB> ReturnHAWBs { get; set; }
    }
}
