//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WareHouseJP.Website.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReturnDetail
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> PackageReturnId { get; set; }
        public Nullable<System.Guid> StoregeJPId { get; set; }
        public Nullable<System.Guid> TrackingDetailId { get; set; }
        public string TrackingSubCode { get; set; }
        public Nullable<double> Weigh { get; set; }
        public string Size { get; set; }
        public string Image { get; set; }
        public byte[] ImageBinary { get; set; }
        public string Notes { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<System.DateTime> SaveDate { get; set; }
        public string SaveHour { get; set; }
        public Nullable<bool> IsReturn { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public string UpdatedBy { get; set; }
    
        public virtual PackageReturn PackageReturn { get; set; }
        public virtual TrackingDetail TrackingDetail { get; set; }
    }
}
