//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WareHouseJP.Website.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShippingBooking
    {
        public System.Guid Id { get; set; }
        public string AgencyId { get; set; }
        public Nullable<System.Guid> ShippingId { get; set; }
        public Nullable<System.DateTime> BookingDate { get; set; }
        public string BookingHour { get; set; }
        public Nullable<double> TrackingCount { get; set; }
        public Nullable<double> Weigh { get; set; }
        public string BookingUser { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public string UpdatedBy { get; set; }
    
        public virtual Shipping Shipping { get; set; }
    }
}
