//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WareHouseJP.Website.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShippingHistory
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> ShippingId { get; set; }
        public string AgencyId { get; set; }
        public string ShippingCode { get; set; }
        public Nullable<System.DateTime> DateAir { get; set; }
        public string HourAir { get; set; }
        public Nullable<System.Guid> FromAirId { get; set; }
        public Nullable<System.Guid> ToAirId { get; set; }
        public Nullable<int> WareHouseInfoId { get; set; }
        public string Notes { get; set; }
        public string MaWBId { get; set; }
        public string PreAD_Note { get; set; }
        public string PreADFile { get; set; }
        public string PreADBase64 { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public string UpdatedBy { get; set; }
    
        public virtual Shipping Shipping { get; set; }
    }
}
