//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tesp.App.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class AgencyAccount
    {
        public string UserName { get; set; }
        public string Password { get; set; }
        public string AgencyId { get; set; }
        public string Name { get; set; }
        public string Avatar { get; set; }
        public byte[] AVatarBinary { get; set; }
        public Nullable<int> RoleId { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public Nullable<bool> Gender { get; set; }
    
        public virtual Agency Agency { get; set; }
        public virtual Role Role { get; set; }
    }
}
