//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tesp.App.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClearanceAir
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> ClearanceId { get; set; }
        public Nullable<System.Guid> FlightBookingId { get; set; }
        public string AgencyId { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string AirFrom { get; set; }
        public string AirTo { get; set; }
        public Nullable<System.DateTime> FlightDateFrom { get; set; }
        public string FlightHourFrom { get; set; }
        public Nullable<System.DateTime> FlightDateTo { get; set; }
        public string FlightHourTo { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public string UpdatedBy { get; set; }
    
        public virtual Agency Agency { get; set; }
        public virtual CustomsClearance CustomsClearance { get; set; }
        public virtual FlightBooking FlightBooking { get; set; }
    }
}
