//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tesp.App.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClearanceHAWB
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> ClearanceId { get; set; }
        public Nullable<System.Guid> FlightBookingId { get; set; }
        public string AgencyId { get; set; }
        public string HAWBId { get; set; }
        public Nullable<bool> IsUse { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
    
        public virtual Agency Agency { get; set; }
        public virtual CustomsClearance CustomsClearance { get; set; }
        public virtual FlightBooking FlightBooking { get; set; }
        public virtual HAWB HAWB { get; set; }
    }
}
