//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tesp.App.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomsClearance
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CustomsClearance()
        {
            this.ClearanceAirs = new HashSet<ClearanceAir>();
            this.ClearanceHAWBs = new HashSet<ClearanceHAWB>();
            this.ClearanceMAWBs = new HashSet<ClearanceMAWB>();
            this.Invoices = new HashSet<Invoice>();
        }
    
        public System.Guid Id { get; set; }
        public string AgencyId { get; set; }
        public Nullable<System.Guid> FlightBookingId { get; set; }
        public string StaffId { get; set; }
        public string StaffIdUpdate { get; set; }
        public string ClearanceCode { get; set; }
        public string AirId { get; set; }
        public string PreAd { get; set; }
        public string Image { get; set; }
        public byte[] ImageBinary { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<bool> IsClearance { get; set; }
        public Nullable<double> Weigh { get; set; }
        public string Size { get; set; }
        public string Notes { get; set; }
        public Nullable<System.DateTime> ClearanceDate { get; set; }
        public Nullable<System.DateTime> ClearanceHour { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
    
        public virtual Agency Agency { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClearanceAir> ClearanceAirs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClearanceHAWB> ClearanceHAWBs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClearanceMAWB> ClearanceMAWBs { get; set; }
        public virtual FlightBooking FlightBooking { get; set; }
        public virtual Staff Staff { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Invoice> Invoices { get; set; }
    }
}
