//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tesp.App.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class StorageJP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StorageJP()
        {
            this.StorageItemJPs = new HashSet<StorageItemJP>();
            this.TrackingDetails = new HashSet<TrackingDetail>();
        }
    
        public System.Guid Id { get; set; }
        public Nullable<int> WareHouseInfoId { get; set; }
        public string StaffId { get; set; }
        public Nullable<int> SizeTableId { get; set; }
        public string AgencyId { get; set; }
        public string TrackingCode { get; set; }
        public string ShippingMark { get; set; }
        public string Notes { get; set; }
        public Nullable<double> Weigh { get; set; }
        public string Size { get; set; }
        public string SizeInput { get; set; }
        public Nullable<double> WeighInput { get; set; }
        public string Image { get; set; }
        public byte[] ImageBinary { get; set; }
        public string ImageBase64 { get; set; }
        public string DeliveryAddress { get; set; }
        public Nullable<bool> IsStaffConfirm { get; set; }
        public Nullable<bool> IsAgencyConfirm { get; set; }
        public Nullable<bool> IsCheck { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<System.DateTime> ReceivedDate { get; set; }
        public string ReceivedHour { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public string UpdatedBy { get; set; }
    
        public virtual Agency Agency { get; set; }
        public virtual SizeTable SizeTable { get; set; }
        public virtual Staff Staff { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StorageItemJP> StorageItemJPs { get; set; }
        public virtual WareHouseInfo WareHouseInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrackingDetail> TrackingDetails { get; set; }
    }
}
