//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tesp.App.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrackingDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TrackingDetail()
        {
            this.ExportGoodDetails = new HashSet<ExportGoodDetail>();
            this.ReturnTrackings = new HashSet<ReturnTracking>();
            this.ReturnTrackings1 = new HashSet<ReturnTracking>();
            this.StorageItemJPs = new HashSet<StorageItemJP>();
        }
    
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> StoregeJPId { get; set; }
        public string TrackingSubCode { get; set; }
        public Nullable<double> Weigh { get; set; }
        public string Size { get; set; }
        public string Image { get; set; }
        public byte[] ImageBinary { get; set; }
        public string Notes { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<System.DateTime> SaveDate { get; set; }
        public string SaveHour { get; set; }
        public Nullable<bool> IsReturn { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public string UpdatedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExportGoodDetail> ExportGoodDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReturnTracking> ReturnTrackings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReturnTracking> ReturnTrackings1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StorageItemJP> StorageItemJPs { get; set; }
        public virtual StorageJP StorageJP { get; set; }
    }
}
