//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tesp.App.db
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WareHouseJPDB : DbContext
    {
        public WareHouseJPDB()
            : base("name=WareHouseJPDB")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Agency> Agencies { get; set; }
        public virtual DbSet<AgencyAccount> AgencyAccounts { get; set; }
        public virtual DbSet<AgencyPackage> AgencyPackages { get; set; }
        public virtual DbSet<AgencyPackageItem> AgencyPackageItems { get; set; }
        public virtual DbSet<AirInfo> AirInfoes { get; set; }
        public virtual DbSet<Booking> Bookings { get; set; }
        public virtual DbSet<ClearanceAir> ClearanceAirs { get; set; }
        public virtual DbSet<ClearanceHAWB> ClearanceHAWBs { get; set; }
        public virtual DbSet<ClearanceMAWB> ClearanceMAWBs { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<CustomsClearance> CustomsClearances { get; set; }
        public virtual DbSet<DeliveryAddress> DeliveryAddresses { get; set; }
        public virtual DbSet<DeliveryCom> DeliveryComs { get; set; }
        public virtual DbSet<EmailHistory> EmailHistories { get; set; }
        public virtual DbSet<EmailSend> EmailSends { get; set; }
        public virtual DbSet<ExportGood> ExportGoods { get; set; }
        public virtual DbSet<ExportGoodDetail> ExportGoodDetails { get; set; }
        public virtual DbSet<ExportInvoice> ExportInvoices { get; set; }
        public virtual DbSet<FlightBooking> FlightBookings { get; set; }
        public virtual DbSet<FlightBookingHAWB> FlightBookingHAWBs { get; set; }
        public virtual DbSet<FlightBookingMAWB> FlightBookingMAWBs { get; set; }
        public virtual DbSet<FlightGood> FlightGoods { get; set; }
        public virtual DbSet<FlightRoute> FlightRoutes { get; set; }
        public virtual DbSet<HAWB> HAWBs { get; set; }
        public virtual DbSet<HAWBDetail> HAWBDetails { get; set; }
        public virtual DbSet<Invoice> Invoices { get; set; }
        public virtual DbSet<MAWB> MAWBs { get; set; }
        public virtual DbSet<MAWBDetail> MAWBDetails { get; set; }
        public virtual DbSet<ProductType> ProductTypes { get; set; }
        public virtual DbSet<ReturnAddress> ReturnAddresses { get; set; }
        public virtual DbSet<ReturnItem> ReturnItems { get; set; }
        public virtual DbSet<ReturnTracking> ReturnTrackings { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Shipment> Shipments { get; set; }
        public virtual DbSet<SizeTable> SizeTables { get; set; }
        public virtual DbSet<Staff> Staffs { get; set; }
        public virtual DbSet<StatusWareHouse> StatusWareHouses { get; set; }
        public virtual DbSet<StorageItemJP> StorageItemJPs { get; set; }
        public virtual DbSet<StorageJP> StorageJPs { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TrackingDetail> TrackingDetails { get; set; }
        public virtual DbSet<WareHouseCategory> WareHouseCategories { get; set; }
        public virtual DbSet<WareHouseInfo> WareHouseInfoes { get; set; }
        public virtual DbSet<WareHouseItem> WareHouseItems { get; set; }
    }
}
