//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WareHouseJP.Website.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;
    public partial class AirInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AirInfo()
        {
            this.ExportGoods = new HashSet<ExportGood>();
        }
        [Required(ErrorMessage ="Vui lòng nhập mã chuyến bay")]
        [Remote("AirInfoId", "CheckExits", ErrorMessage = "Mã chuyến bay đã tồn tại")]
        public string Id { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập tên chuyến bay")]
        public string Name { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập nơi đi")]
        public string AirFrom { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập nơi đến")]
        public string AirTo { get; set; }
        [Required(ErrorMessage = "Vui lòng chọn ngày bay")]
        [DataType(DataType.DateTime)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:yyyy-MM-dd}")]
        public Nullable<System.DateTime> FlightDateFrom { get; set; }
        [Required(ErrorMessage = "Vui lòng chọn giờ bay")]
        public string FlightHourFrom { get; set; }
        [Required(ErrorMessage = "Vui lòng chọn ngày đến")]
        [DataType(DataType.DateTime)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:yyyy-MM-dd}")]
        public Nullable<System.DateTime> FlightDateTo { get; set; }
        [Required(ErrorMessage = "Vui lòng chọn giờ đến")]
        public string FlightHourTo { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public string UpdatedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExportGood> ExportGoods { get; set; }
    }
}
