//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WareHouseJP.Website.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;
    public partial class StorageJP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StorageJP()
        {
            this.StorageItemJPs = new HashSet<StorageItemJP>();
            this.TrackingDetails = new HashSet<TrackingDetail>();
        }
    
        public System.Guid Id { get; set; }
        public Nullable<int> WareHouseInfoId { get; set; }
        public string StaffId { get; set; }
        public Nullable<int> SizeTableId { get; set; }
        public string AgencyId { get; set; }
        [Required(ErrorMessage ="Vui lòng nhập mã tracking")]
        [Remote("StoreJPTrackingCode", "CheckExits", ErrorMessage = "Mã tracking đã tồn tại")]
        public string TrackingCode { get; set; }
        public string Notes { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập khối lượng")]
        public string Weigh { get; set; }
        public string Size { get; set; }
        public string Image { get; set; }
        [Required(ErrorMessage = "Vui lòng chọn địa chỉ")]
        [Remote("StoreJPDeliveryAddress", "CheckExits", ErrorMessage = "Vui lòng chọn địa chỉ")]
        public string DeliveryAddress { get; set; }
        public Nullable<bool> IsStaffConfirm { get; set; }
        public Nullable<bool> IsAgencyConfirm { get; set; }
        public Nullable<int> StatusId { get; set; }
        [Required(ErrorMessage = "Vui lòng chọn ngày nhận hàng")]
        [DataType(DataType.DateTime)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:yyyy-MM-dd}")]
        public Nullable<System.DateTime> ReceivedDate { get; set; }
        [Required(ErrorMessage = "Vui lòng chọn giờ nhận hàng")]
        public string ReceivedHour { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public string UpdatedBy { get; set; }
    
        public virtual Agency Agency { get; set; }
        public virtual SizeTable SizeTable { get; set; }
        public virtual Staff Staff { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StorageItemJP> StorageItemJPs { get; set; }
        public virtual WareHouseInfo WareHouseInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrackingDetail> TrackingDetails { get; set; }
    }
}
