//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WareHouseJP.Website.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class TrackingStatu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TrackingStatu()
        {
            this.AgencyPackages = new HashSet<AgencyPackage>();
        }
    
        public int Id { get; set; }
        [Required(ErrorMessage ="Vui lòng nhập tên trạng thái")]
        public string Name { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập tên thứ tự")]
        [RegularExpression("^\\d+$", ErrorMessage = "Vui lòng nhập thứ tự là số")]
        public Nullable<int> NoOrder { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public string UpdatedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AgencyPackage> AgencyPackages { get; set; }
    }
}
