//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ohayoo.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        public int id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public Nullable<int> levelCate { get; set; }
        public Nullable<int> parent_id { get; set; }
        public Nullable<bool> status { get; set; }
        public Nullable<bool> is_leaf { get; set; }
    }
}
