//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ohayoo.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExchageRate
    {
        public int id { get; set; }
        public Nullable<double> exRate { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
    }
}
