//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ohayoo.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ohayoo_Category
    {
        public int auto { get; set; }
        public string id { get; set; }
        public string name_jp { get; set; }
        public string name_en { get; set; }
        public string name_vn { get; set; }
        public string url { get; set; }
        public string website { get; set; }
    }
}
